export const packages = [
  {
    id: 1,
    name: "QBASIC (S1) — Quick Fit Qualification",
    price: "₹9,999",
    period: "one-time",
    description:
      "Perfect if you want to stop wasting time on unqualified enquiries.",
    recommended: false,

    features: [
      { text: "AI-powered instant lead engagement", included: true },
      { text: "S1 qualification logic (Quick Fit screening)", included: true },
      {
        text: "Intelligent greeting & basic discovery questions",
        included: true,
      },
      {
        text: "Instant response to FAQs using approved content",
        included: true,
      },
      { text: "Lead grading (A / B / C)", included: true },
      { text: "Auto-capture of lead details", included: true },
      { text: "Dashboard access with lead visibility", included: true },
      { text: "Qualified & unqualified lead tracking", included: true },
    ],
    bestForTitle: "Best for",
    bestForItems: [
      "Small businesses",
      "Low to mid-ticket offerings",
      "First-time AI adoption",
      "High enquiry volume with basic filtering needs",
    ],
    s1DoesBestTitle: "What S1 Does Best",
    s1DoesBestItems: [
      "Filters serious vs casual enquiries",
      "Eliminates junk and accidental clicks",
      "Ensures your team calls only relevant leads",
    ],
  },
  {
    id: 2,
    name: "QSTART (S2) — Structured Discovery & Intent Validation",
    price: "₹12,999",
    period: "one-time",
    description: "Deal for teams that want fewer calls and better conversions.",
    recommended: true,
    features: [
      { text: "Everything in QBASIC, plus:", included: true },
      { text: "S2 qualification logic (Detailed Discovery)", included: true },
      { text: "Budget, timeline & requirement validation", included: true },
      { text: "Motivation and buying intent analysis", included: true },
      { text: "Authority check (decision maker / influencer)", included: true },
      { text: "Real-time intent scoring", included: true },
      { text: "Smart routing for high-intent leads", included: true },
      { text: "CRM sync with full conversation transcripts", included: true },
      { text: "Advanced dashboard metrics", included: true },
    ],
    bestForTitle: "Best for",
    bestForItems: [
      "Growing businesses",
      "Mid-ticket products & services",
      "Sales teams that need context before calling",
      "Conversion-focused campaigns",
    ],
    s2DoesBestTitle: "What S2 Does Best",
    s2DoesBestItems: [
      "Converts enquiries into sales-ready conversations",
      "Gives your sales team context before the first call",
      "Improves close rates with better-qualified leads",
    ],
  },
  {
    id: 3,
    name: "QCORP (S3) — Deep Profiling for High-Value Sales",
    price: "₹19,999",
    period: "one-time",
    description:
      "Built for businesses where every lead has serious revenue potential.",
    recommended: false,
    features: [
      { text: "Everything in QSTART, plus:", included: true },
      { text: "S3 qualification logic (Deep Profiling)", included: true },
      { text: "Advanced preference & use-case capture", included: true },
      { text: "Multi-layer intent validation", included: true },
      { text: "High-value opportunity identification", included: true },
      { text: "Meeting or call scheduling (where applicable)", included: true },
      { text: "Priority AI handling", included: true },
      { text: "Enterprise-grade reporting", included: true },
      { text: "Custom qualification rules", included: true },
      { text: "Dedicated AI design alignment", included: true },
    ],
    bestForTitle: "Best for",
    bestForItems: [
      "High-ticket & enterprise sales",
      "Complex offerings",
      "Longer sales cycles",
      "Teams focused on deal quality over volume",
    ],
    s3DoesBestTitle: "What S3 Does Best",
    s3DoesBestItems: [
      "Identifies true buying intent",
      "Surfaces high-value opportunities early",
      "Reduces sales cycle length",
      "Supports enterprise-level selling",
    ],
  },
];
